/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsPrivacyRouteImport } from './routes/terms-privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedRechargeIndexRouteImport } from './routes/_authed/recharge/index'
import { Route as AuthedChipIndexRouteImport } from './routes/_authed/chip/index'
import { Route as AuthedRechargeHistoryRouteImport } from './routes/_authed/recharge/history'
import { Route as AuthedOperatorDashboardRouteImport } from './routes/_authed/operator/dashboard'
import { Route as AuthedChipHistoryRouteImport } from './routes/_authed/chip/history'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/admin/dashboard'
import { Route as AuthedAdminUserIndexRouteImport } from './routes/_authed/admin/user/index'
import { Route as AuthedAdminRewardsIndexRouteImport } from './routes/_authed/admin/rewards/index'
import { Route as AuthedAdminRechargeIndexRouteImport } from './routes/_authed/admin/recharge/index'
import { Route as AuthedAdminPaymentDestinationsIndexRouteImport } from './routes/_authed/admin/payment-destinations/index'
import { Route as AuthedAdminChipIndexRouteImport } from './routes/_authed/admin/chip/index'
import { Route as AuthedAdminCasinosIndexRouteImport } from './routes/_authed/admin/casinos/index'
import { Route as AuthedAdminRewardsNewRouteImport } from './routes/_authed/admin/rewards/new'
import { Route as AuthedAdminRechargeIdRouteImport } from './routes/_authed/admin/recharge/$id'
import { Route as AuthedAdminPaymentDestinationsNewRouteImport } from './routes/_authed/admin/payment-destinations/new'
import { Route as AuthedAdminChipIdRouteImport } from './routes/_authed/admin/chip/$id'
import { Route as AuthedAdminCasinosNewRouteImport } from './routes/_authed/admin/casinos/new'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsPrivacyRoute = TermsPrivacyRouteImport.update({
  id: '/terms-privacy',
  path: '/terms-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRechargeIndexRoute = AuthedRechargeIndexRouteImport.update({
  id: '/recharge/',
  path: '/recharge/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChipIndexRoute = AuthedChipIndexRouteImport.update({
  id: '/chip/',
  path: '/chip/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRechargeHistoryRoute = AuthedRechargeHistoryRouteImport.update({
  id: '/recharge/history',
  path: '/recharge/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperatorDashboardRoute = AuthedOperatorDashboardRouteImport.update({
  id: '/operator/dashboard',
  path: '/operator/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChipHistoryRoute = AuthedChipHistoryRouteImport.update({
  id: '/chip/history',
  path: '/chip/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUserIndexRoute = AuthedAdminUserIndexRouteImport.update({
  id: '/admin/user/',
  path: '/admin/user/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRewardsIndexRoute = AuthedAdminRewardsIndexRouteImport.update({
  id: '/admin/rewards/',
  path: '/admin/rewards/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRechargeIndexRoute =
  AuthedAdminRechargeIndexRouteImport.update({
    id: '/admin/recharge/',
    path: '/admin/recharge/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminPaymentDestinationsIndexRoute =
  AuthedAdminPaymentDestinationsIndexRouteImport.update({
    id: '/admin/payment-destinations/',
    path: '/admin/payment-destinations/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminChipIndexRoute = AuthedAdminChipIndexRouteImport.update({
  id: '/admin/chip/',
  path: '/admin/chip/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCasinosIndexRoute = AuthedAdminCasinosIndexRouteImport.update({
  id: '/admin/casinos/',
  path: '/admin/casinos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRewardsNewRoute = AuthedAdminRewardsNewRouteImport.update({
  id: '/admin/rewards/new',
  path: '/admin/rewards/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRechargeIdRoute = AuthedAdminRechargeIdRouteImport.update({
  id: '/admin/recharge/$id',
  path: '/admin/recharge/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPaymentDestinationsNewRoute =
  AuthedAdminPaymentDestinationsNewRouteImport.update({
    id: '/admin/payment-destinations/new',
    path: '/admin/payment-destinations/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminChipIdRoute = AuthedAdminChipIdRouteImport.update({
  id: '/admin/chip/$id',
  path: '/admin/chip/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCasinosNewRoute = AuthedAdminCasinosNewRouteImport.update({
  id: '/admin/casinos/new',
  path: '/admin/casinos/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/terms-privacy': typeof TermsPrivacyRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/chip/history': typeof AuthedChipHistoryRoute
  '/operator/dashboard': typeof AuthedOperatorDashboardRoute
  '/recharge/history': typeof AuthedRechargeHistoryRoute
  '/chip/': typeof AuthedChipIndexRoute
  '/recharge/': typeof AuthedRechargeIndexRoute
  '/admin/casinos/new': typeof AuthedAdminCasinosNewRoute
  '/admin/chip/$id': typeof AuthedAdminChipIdRoute
  '/admin/payment-destinations/new': typeof AuthedAdminPaymentDestinationsNewRoute
  '/admin/recharge/$id': typeof AuthedAdminRechargeIdRoute
  '/admin/rewards/new': typeof AuthedAdminRewardsNewRoute
  '/admin/casinos/': typeof AuthedAdminCasinosIndexRoute
  '/admin/chip/': typeof AuthedAdminChipIndexRoute
  '/admin/payment-destinations/': typeof AuthedAdminPaymentDestinationsIndexRoute
  '/admin/recharge/': typeof AuthedAdminRechargeIndexRoute
  '/admin/rewards/': typeof AuthedAdminRewardsIndexRoute
  '/admin/user/': typeof AuthedAdminUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/terms-privacy': typeof TermsPrivacyRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/chip/history': typeof AuthedChipHistoryRoute
  '/operator/dashboard': typeof AuthedOperatorDashboardRoute
  '/recharge/history': typeof AuthedRechargeHistoryRoute
  '/chip': typeof AuthedChipIndexRoute
  '/recharge': typeof AuthedRechargeIndexRoute
  '/admin/casinos/new': typeof AuthedAdminCasinosNewRoute
  '/admin/chip/$id': typeof AuthedAdminChipIdRoute
  '/admin/payment-destinations/new': typeof AuthedAdminPaymentDestinationsNewRoute
  '/admin/recharge/$id': typeof AuthedAdminRechargeIdRoute
  '/admin/rewards/new': typeof AuthedAdminRewardsNewRoute
  '/admin/casinos': typeof AuthedAdminCasinosIndexRoute
  '/admin/chip': typeof AuthedAdminChipIndexRoute
  '/admin/payment-destinations': typeof AuthedAdminPaymentDestinationsIndexRoute
  '/admin/recharge': typeof AuthedAdminRechargeIndexRoute
  '/admin/rewards': typeof AuthedAdminRewardsIndexRoute
  '/admin/user': typeof AuthedAdminUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/terms-privacy': typeof TermsPrivacyRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/chip/history': typeof AuthedChipHistoryRoute
  '/_authed/operator/dashboard': typeof AuthedOperatorDashboardRoute
  '/_authed/recharge/history': typeof AuthedRechargeHistoryRoute
  '/_authed/chip/': typeof AuthedChipIndexRoute
  '/_authed/recharge/': typeof AuthedRechargeIndexRoute
  '/_authed/admin/casinos/new': typeof AuthedAdminCasinosNewRoute
  '/_authed/admin/chip/$id': typeof AuthedAdminChipIdRoute
  '/_authed/admin/payment-destinations/new': typeof AuthedAdminPaymentDestinationsNewRoute
  '/_authed/admin/recharge/$id': typeof AuthedAdminRechargeIdRoute
  '/_authed/admin/rewards/new': typeof AuthedAdminRewardsNewRoute
  '/_authed/admin/casinos/': typeof AuthedAdminCasinosIndexRoute
  '/_authed/admin/chip/': typeof AuthedAdminChipIndexRoute
  '/_authed/admin/payment-destinations/': typeof AuthedAdminPaymentDestinationsIndexRoute
  '/_authed/admin/recharge/': typeof AuthedAdminRechargeIndexRoute
  '/_authed/admin/rewards/': typeof AuthedAdminRewardsIndexRoute
  '/_authed/admin/user/': typeof AuthedAdminUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/rewards'
    | '/signup'
    | '/terms-privacy'
    | '/update-password'
    | '/dashboard'
    | '/transactions'
    | '/admin/dashboard'
    | '/chip/history'
    | '/operator/dashboard'
    | '/recharge/history'
    | '/chip/'
    | '/recharge/'
    | '/admin/casinos/new'
    | '/admin/chip/$id'
    | '/admin/payment-destinations/new'
    | '/admin/recharge/$id'
    | '/admin/rewards/new'
    | '/admin/casinos/'
    | '/admin/chip/'
    | '/admin/payment-destinations/'
    | '/admin/recharge/'
    | '/admin/rewards/'
    | '/admin/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/rewards'
    | '/signup'
    | '/terms-privacy'
    | '/update-password'
    | '/dashboard'
    | '/transactions'
    | '/admin/dashboard'
    | '/chip/history'
    | '/operator/dashboard'
    | '/recharge/history'
    | '/chip'
    | '/recharge'
    | '/admin/casinos/new'
    | '/admin/chip/$id'
    | '/admin/payment-destinations/new'
    | '/admin/recharge/$id'
    | '/admin/rewards/new'
    | '/admin/casinos'
    | '/admin/chip'
    | '/admin/payment-destinations'
    | '/admin/recharge'
    | '/admin/rewards'
    | '/admin/user'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/error'
    | '/login'
    | '/logout'
    | '/rewards'
    | '/signup'
    | '/terms-privacy'
    | '/update-password'
    | '/_authed/dashboard'
    | '/_authed/transactions'
    | '/_authed/admin/dashboard'
    | '/_authed/chip/history'
    | '/_authed/operator/dashboard'
    | '/_authed/recharge/history'
    | '/_authed/chip/'
    | '/_authed/recharge/'
    | '/_authed/admin/casinos/new'
    | '/_authed/admin/chip/$id'
    | '/_authed/admin/payment-destinations/new'
    | '/_authed/admin/recharge/$id'
    | '/_authed/admin/rewards/new'
    | '/_authed/admin/casinos/'
    | '/_authed/admin/chip/'
    | '/_authed/admin/payment-destinations/'
    | '/_authed/admin/recharge/'
    | '/_authed/admin/rewards/'
    | '/_authed/admin/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RewardsRoute: typeof RewardsRoute
  SignupRoute: typeof SignupRoute
  TermsPrivacyRoute: typeof TermsPrivacyRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-privacy': {
      id: '/terms-privacy'
      path: '/terms-privacy'
      fullPath: '/terms-privacy'
      preLoaderRoute: typeof TermsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recharge/': {
      id: '/_authed/recharge/'
      path: '/recharge'
      fullPath: '/recharge/'
      preLoaderRoute: typeof AuthedRechargeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chip/': {
      id: '/_authed/chip/'
      path: '/chip'
      fullPath: '/chip/'
      preLoaderRoute: typeof AuthedChipIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recharge/history': {
      id: '/_authed/recharge/history'
      path: '/recharge/history'
      fullPath: '/recharge/history'
      preLoaderRoute: typeof AuthedRechargeHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operator/dashboard': {
      id: '/_authed/operator/dashboard'
      path: '/operator/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof AuthedOperatorDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chip/history': {
      id: '/_authed/chip/history'
      path: '/chip/history'
      fullPath: '/chip/history'
      preLoaderRoute: typeof AuthedChipHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dashboard': {
      id: '/_authed/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/user/': {
      id: '/_authed/admin/user/'
      path: '/admin/user'
      fullPath: '/admin/user/'
      preLoaderRoute: typeof AuthedAdminUserIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/rewards/': {
      id: '/_authed/admin/rewards/'
      path: '/admin/rewards'
      fullPath: '/admin/rewards/'
      preLoaderRoute: typeof AuthedAdminRewardsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/recharge/': {
      id: '/_authed/admin/recharge/'
      path: '/admin/recharge'
      fullPath: '/admin/recharge/'
      preLoaderRoute: typeof AuthedAdminRechargeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/payment-destinations/': {
      id: '/_authed/admin/payment-destinations/'
      path: '/admin/payment-destinations'
      fullPath: '/admin/payment-destinations/'
      preLoaderRoute: typeof AuthedAdminPaymentDestinationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/chip/': {
      id: '/_authed/admin/chip/'
      path: '/admin/chip'
      fullPath: '/admin/chip/'
      preLoaderRoute: typeof AuthedAdminChipIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/casinos/': {
      id: '/_authed/admin/casinos/'
      path: '/admin/casinos'
      fullPath: '/admin/casinos/'
      preLoaderRoute: typeof AuthedAdminCasinosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/rewards/new': {
      id: '/_authed/admin/rewards/new'
      path: '/admin/rewards/new'
      fullPath: '/admin/rewards/new'
      preLoaderRoute: typeof AuthedAdminRewardsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/recharge/$id': {
      id: '/_authed/admin/recharge/$id'
      path: '/admin/recharge/$id'
      fullPath: '/admin/recharge/$id'
      preLoaderRoute: typeof AuthedAdminRechargeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/payment-destinations/new': {
      id: '/_authed/admin/payment-destinations/new'
      path: '/admin/payment-destinations/new'
      fullPath: '/admin/payment-destinations/new'
      preLoaderRoute: typeof AuthedAdminPaymentDestinationsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/chip/$id': {
      id: '/_authed/admin/chip/$id'
      path: '/admin/chip/$id'
      fullPath: '/admin/chip/$id'
      preLoaderRoute: typeof AuthedAdminChipIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/casinos/new': {
      id: '/_authed/admin/casinos/new'
      path: '/admin/casinos/new'
      fullPath: '/admin/casinos/new'
      preLoaderRoute: typeof AuthedAdminCasinosNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedChipHistoryRoute: typeof AuthedChipHistoryRoute
  AuthedOperatorDashboardRoute: typeof AuthedOperatorDashboardRoute
  AuthedRechargeHistoryRoute: typeof AuthedRechargeHistoryRoute
  AuthedChipIndexRoute: typeof AuthedChipIndexRoute
  AuthedRechargeIndexRoute: typeof AuthedRechargeIndexRoute
  AuthedAdminCasinosNewRoute: typeof AuthedAdminCasinosNewRoute
  AuthedAdminChipIdRoute: typeof AuthedAdminChipIdRoute
  AuthedAdminPaymentDestinationsNewRoute: typeof AuthedAdminPaymentDestinationsNewRoute
  AuthedAdminRechargeIdRoute: typeof AuthedAdminRechargeIdRoute
  AuthedAdminRewardsNewRoute: typeof AuthedAdminRewardsNewRoute
  AuthedAdminCasinosIndexRoute: typeof AuthedAdminCasinosIndexRoute
  AuthedAdminChipIndexRoute: typeof AuthedAdminChipIndexRoute
  AuthedAdminPaymentDestinationsIndexRoute: typeof AuthedAdminPaymentDestinationsIndexRoute
  AuthedAdminRechargeIndexRoute: typeof AuthedAdminRechargeIndexRoute
  AuthedAdminRewardsIndexRoute: typeof AuthedAdminRewardsIndexRoute
  AuthedAdminUserIndexRoute: typeof AuthedAdminUserIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedChipHistoryRoute: AuthedChipHistoryRoute,
  AuthedOperatorDashboardRoute: AuthedOperatorDashboardRoute,
  AuthedRechargeHistoryRoute: AuthedRechargeHistoryRoute,
  AuthedChipIndexRoute: AuthedChipIndexRoute,
  AuthedRechargeIndexRoute: AuthedRechargeIndexRoute,
  AuthedAdminCasinosNewRoute: AuthedAdminCasinosNewRoute,
  AuthedAdminChipIdRoute: AuthedAdminChipIdRoute,
  AuthedAdminPaymentDestinationsNewRoute:
    AuthedAdminPaymentDestinationsNewRoute,
  AuthedAdminRechargeIdRoute: AuthedAdminRechargeIdRoute,
  AuthedAdminRewardsNewRoute: AuthedAdminRewardsNewRoute,
  AuthedAdminCasinosIndexRoute: AuthedAdminCasinosIndexRoute,
  AuthedAdminChipIndexRoute: AuthedAdminChipIndexRoute,
  AuthedAdminPaymentDestinationsIndexRoute:
    AuthedAdminPaymentDestinationsIndexRoute,
  AuthedAdminRechargeIndexRoute: AuthedAdminRechargeIndexRoute,
  AuthedAdminRewardsIndexRoute: AuthedAdminRewardsIndexRoute,
  AuthedAdminUserIndexRoute: AuthedAdminUserIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RewardsRoute: RewardsRoute,
  SignupRoute: SignupRoute,
  TermsPrivacyRoute: TermsPrivacyRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
