/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedRechargeIndexRouteImport } from './routes/_authed/recharge/index'
import { Route as AuthedRechargeHistoryRouteImport } from './routes/_authed/recharge/history'
import { Route as AuthedOperatorDashboardRouteImport } from './routes/_authed/operator/dashboard'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/admin/dashboard'
import { Route as AuthedAdminRewardsIndexRouteImport } from './routes/_authed/admin/rewards/index'
import { Route as AuthedAdminRechargeIndexRouteImport } from './routes/_authed/admin/recharge/index'
import { Route as AuthedAdminPaymentDestinationsIndexRouteImport } from './routes/_authed/admin/payment-destinations/index'
import { Route as AuthedAdminCasinosIndexRouteImport } from './routes/_authed/admin/casinos/index'
import { Route as AuthedAdminUserGivePointsRouteImport } from './routes/_authed/admin/user/give-points'
import { Route as AuthedAdminRewardsNewRouteImport } from './routes/_authed/admin/rewards/new'
import { Route as AuthedAdminRechargeIdRouteImport } from './routes/_authed/admin/recharge/$id'
import { Route as AuthedAdminPaymentDestinationsNewRouteImport } from './routes/_authed/admin/payment-destinations/new'
import { Route as AuthedAdminCasinosNewRouteImport } from './routes/_authed/admin/casinos/new'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRechargeIndexRoute = AuthedRechargeIndexRouteImport.update({
  id: '/recharge/',
  path: '/recharge/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRechargeHistoryRoute = AuthedRechargeHistoryRouteImport.update({
  id: '/recharge/history',
  path: '/recharge/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperatorDashboardRoute = AuthedOperatorDashboardRouteImport.update({
  id: '/operator/dashboard',
  path: '/operator/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRewardsIndexRoute = AuthedAdminRewardsIndexRouteImport.update({
  id: '/admin/rewards/',
  path: '/admin/rewards/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRechargeIndexRoute =
  AuthedAdminRechargeIndexRouteImport.update({
    id: '/admin/recharge/',
    path: '/admin/recharge/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminPaymentDestinationsIndexRoute =
  AuthedAdminPaymentDestinationsIndexRouteImport.update({
    id: '/admin/payment-destinations/',
    path: '/admin/payment-destinations/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminCasinosIndexRoute = AuthedAdminCasinosIndexRouteImport.update({
  id: '/admin/casinos/',
  path: '/admin/casinos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUserGivePointsRoute =
  AuthedAdminUserGivePointsRouteImport.update({
    id: '/admin/user/give-points',
    path: '/admin/user/give-points',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminRewardsNewRoute = AuthedAdminRewardsNewRouteImport.update({
  id: '/admin/rewards/new',
  path: '/admin/rewards/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRechargeIdRoute = AuthedAdminRechargeIdRouteImport.update({
  id: '/admin/recharge/$id',
  path: '/admin/recharge/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPaymentDestinationsNewRoute =
  AuthedAdminPaymentDestinationsNewRouteImport.update({
    id: '/admin/payment-destinations/new',
    path: '/admin/payment-destinations/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminCasinosNewRoute = AuthedAdminCasinosNewRouteImport.update({
  id: '/admin/casinos/new',
  path: '/admin/casinos/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/operator/dashboard': typeof AuthedOperatorDashboardRoute
  '/recharge/history': typeof AuthedRechargeHistoryRoute
  '/recharge/': typeof AuthedRechargeIndexRoute
  '/admin/casinos/new': typeof AuthedAdminCasinosNewRoute
  '/admin/payment-destinations/new': typeof AuthedAdminPaymentDestinationsNewRoute
  '/admin/recharge/$id': typeof AuthedAdminRechargeIdRoute
  '/admin/rewards/new': typeof AuthedAdminRewardsNewRoute
  '/admin/user/give-points': typeof AuthedAdminUserGivePointsRoute
  '/admin/casinos/': typeof AuthedAdminCasinosIndexRoute
  '/admin/payment-destinations/': typeof AuthedAdminPaymentDestinationsIndexRoute
  '/admin/recharge/': typeof AuthedAdminRechargeIndexRoute
  '/admin/rewards/': typeof AuthedAdminRewardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/operator/dashboard': typeof AuthedOperatorDashboardRoute
  '/recharge/history': typeof AuthedRechargeHistoryRoute
  '/recharge': typeof AuthedRechargeIndexRoute
  '/admin/casinos/new': typeof AuthedAdminCasinosNewRoute
  '/admin/payment-destinations/new': typeof AuthedAdminPaymentDestinationsNewRoute
  '/admin/recharge/$id': typeof AuthedAdminRechargeIdRoute
  '/admin/rewards/new': typeof AuthedAdminRewardsNewRoute
  '/admin/user/give-points': typeof AuthedAdminUserGivePointsRoute
  '/admin/casinos': typeof AuthedAdminCasinosIndexRoute
  '/admin/payment-destinations': typeof AuthedAdminPaymentDestinationsIndexRoute
  '/admin/recharge': typeof AuthedAdminRechargeIndexRoute
  '/admin/rewards': typeof AuthedAdminRewardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/operator/dashboard': typeof AuthedOperatorDashboardRoute
  '/_authed/recharge/history': typeof AuthedRechargeHistoryRoute
  '/_authed/recharge/': typeof AuthedRechargeIndexRoute
  '/_authed/admin/casinos/new': typeof AuthedAdminCasinosNewRoute
  '/_authed/admin/payment-destinations/new': typeof AuthedAdminPaymentDestinationsNewRoute
  '/_authed/admin/recharge/$id': typeof AuthedAdminRechargeIdRoute
  '/_authed/admin/rewards/new': typeof AuthedAdminRewardsNewRoute
  '/_authed/admin/user/give-points': typeof AuthedAdminUserGivePointsRoute
  '/_authed/admin/casinos/': typeof AuthedAdminCasinosIndexRoute
  '/_authed/admin/payment-destinations/': typeof AuthedAdminPaymentDestinationsIndexRoute
  '/_authed/admin/recharge/': typeof AuthedAdminRechargeIndexRoute
  '/_authed/admin/rewards/': typeof AuthedAdminRewardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/rewards'
    | '/signup'
    | '/update-password'
    | '/dashboard'
    | '/transactions'
    | '/admin/dashboard'
    | '/operator/dashboard'
    | '/recharge/history'
    | '/recharge/'
    | '/admin/casinos/new'
    | '/admin/payment-destinations/new'
    | '/admin/recharge/$id'
    | '/admin/rewards/new'
    | '/admin/user/give-points'
    | '/admin/casinos/'
    | '/admin/payment-destinations/'
    | '/admin/recharge/'
    | '/admin/rewards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/rewards'
    | '/signup'
    | '/update-password'
    | '/dashboard'
    | '/transactions'
    | '/admin/dashboard'
    | '/operator/dashboard'
    | '/recharge/history'
    | '/recharge'
    | '/admin/casinos/new'
    | '/admin/payment-destinations/new'
    | '/admin/recharge/$id'
    | '/admin/rewards/new'
    | '/admin/user/give-points'
    | '/admin/casinos'
    | '/admin/payment-destinations'
    | '/admin/recharge'
    | '/admin/rewards'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/rewards'
    | '/signup'
    | '/update-password'
    | '/_authed/dashboard'
    | '/_authed/transactions'
    | '/_authed/admin/dashboard'
    | '/_authed/operator/dashboard'
    | '/_authed/recharge/history'
    | '/_authed/recharge/'
    | '/_authed/admin/casinos/new'
    | '/_authed/admin/payment-destinations/new'
    | '/_authed/admin/recharge/$id'
    | '/_authed/admin/rewards/new'
    | '/_authed/admin/user/give-points'
    | '/_authed/admin/casinos/'
    | '/_authed/admin/payment-destinations/'
    | '/_authed/admin/recharge/'
    | '/_authed/admin/rewards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RewardsRoute: typeof RewardsRoute
  SignupRoute: typeof SignupRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recharge/': {
      id: '/_authed/recharge/'
      path: '/recharge'
      fullPath: '/recharge/'
      preLoaderRoute: typeof AuthedRechargeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recharge/history': {
      id: '/_authed/recharge/history'
      path: '/recharge/history'
      fullPath: '/recharge/history'
      preLoaderRoute: typeof AuthedRechargeHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operator/dashboard': {
      id: '/_authed/operator/dashboard'
      path: '/operator/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof AuthedOperatorDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dashboard': {
      id: '/_authed/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/rewards/': {
      id: '/_authed/admin/rewards/'
      path: '/admin/rewards'
      fullPath: '/admin/rewards/'
      preLoaderRoute: typeof AuthedAdminRewardsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/recharge/': {
      id: '/_authed/admin/recharge/'
      path: '/admin/recharge'
      fullPath: '/admin/recharge/'
      preLoaderRoute: typeof AuthedAdminRechargeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/payment-destinations/': {
      id: '/_authed/admin/payment-destinations/'
      path: '/admin/payment-destinations'
      fullPath: '/admin/payment-destinations/'
      preLoaderRoute: typeof AuthedAdminPaymentDestinationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/casinos/': {
      id: '/_authed/admin/casinos/'
      path: '/admin/casinos'
      fullPath: '/admin/casinos/'
      preLoaderRoute: typeof AuthedAdminCasinosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/user/give-points': {
      id: '/_authed/admin/user/give-points'
      path: '/admin/user/give-points'
      fullPath: '/admin/user/give-points'
      preLoaderRoute: typeof AuthedAdminUserGivePointsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/rewards/new': {
      id: '/_authed/admin/rewards/new'
      path: '/admin/rewards/new'
      fullPath: '/admin/rewards/new'
      preLoaderRoute: typeof AuthedAdminRewardsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/recharge/$id': {
      id: '/_authed/admin/recharge/$id'
      path: '/admin/recharge/$id'
      fullPath: '/admin/recharge/$id'
      preLoaderRoute: typeof AuthedAdminRechargeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/payment-destinations/new': {
      id: '/_authed/admin/payment-destinations/new'
      path: '/admin/payment-destinations/new'
      fullPath: '/admin/payment-destinations/new'
      preLoaderRoute: typeof AuthedAdminPaymentDestinationsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/casinos/new': {
      id: '/_authed/admin/casinos/new'
      path: '/admin/casinos/new'
      fullPath: '/admin/casinos/new'
      preLoaderRoute: typeof AuthedAdminCasinosNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedOperatorDashboardRoute: typeof AuthedOperatorDashboardRoute
  AuthedRechargeHistoryRoute: typeof AuthedRechargeHistoryRoute
  AuthedRechargeIndexRoute: typeof AuthedRechargeIndexRoute
  AuthedAdminCasinosNewRoute: typeof AuthedAdminCasinosNewRoute
  AuthedAdminPaymentDestinationsNewRoute: typeof AuthedAdminPaymentDestinationsNewRoute
  AuthedAdminRechargeIdRoute: typeof AuthedAdminRechargeIdRoute
  AuthedAdminRewardsNewRoute: typeof AuthedAdminRewardsNewRoute
  AuthedAdminUserGivePointsRoute: typeof AuthedAdminUserGivePointsRoute
  AuthedAdminCasinosIndexRoute: typeof AuthedAdminCasinosIndexRoute
  AuthedAdminPaymentDestinationsIndexRoute: typeof AuthedAdminPaymentDestinationsIndexRoute
  AuthedAdminRechargeIndexRoute: typeof AuthedAdminRechargeIndexRoute
  AuthedAdminRewardsIndexRoute: typeof AuthedAdminRewardsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedOperatorDashboardRoute: AuthedOperatorDashboardRoute,
  AuthedRechargeHistoryRoute: AuthedRechargeHistoryRoute,
  AuthedRechargeIndexRoute: AuthedRechargeIndexRoute,
  AuthedAdminCasinosNewRoute: AuthedAdminCasinosNewRoute,
  AuthedAdminPaymentDestinationsNewRoute:
    AuthedAdminPaymentDestinationsNewRoute,
  AuthedAdminRechargeIdRoute: AuthedAdminRechargeIdRoute,
  AuthedAdminRewardsNewRoute: AuthedAdminRewardsNewRoute,
  AuthedAdminUserGivePointsRoute: AuthedAdminUserGivePointsRoute,
  AuthedAdminCasinosIndexRoute: AuthedAdminCasinosIndexRoute,
  AuthedAdminPaymentDestinationsIndexRoute:
    AuthedAdminPaymentDestinationsIndexRoute,
  AuthedAdminRechargeIndexRoute: AuthedAdminRechargeIndexRoute,
  AuthedAdminRewardsIndexRoute: AuthedAdminRewardsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RewardsRoute: RewardsRoute,
  SignupRoute: SignupRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
